#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

if ! command -v supabase >/dev/null 2>&1; then
    echo "Supabase CLI not found. Install with: npm i -g supabase"
    exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
    echo "Docker not found. Install Docker Desktop and retry."
    exit 1
fi

if ! docker info >/dev/null 2>&1; then
    echo "Docker isn't running. Start Docker Desktop and retry."
    exit 1
fi

if ! supabase status >/dev/null 2>&1; then
    echo "Starting local Supabase (first run can take a while)..."
    supabase start
fi

status_env="$(supabase status -o env)"

api_url="$(printf '%s\n' "$status_env" | awk -F= '$1=="API_URL"{print $2; exit}')"
if [ -z "$api_url" ]; then
    api_url="$(printf '%s\n' "$status_env" | awk -F= '$1=="SUPABASE_URL"{print $2; exit}')"
fi

anon_key="$(printf '%s\n' "$status_env" | awk -F= '$1=="ANON_KEY"{print $2; exit}')"
if [ -z "$anon_key" ]; then
    anon_key="$(printf '%s\n' "$status_env" | awk -F= '$1=="SUPABASE_ANON_KEY"{print $2; exit}')"
fi

service_role_key="$(printf '%s\n' "$status_env" | awk -F= '$1=="SERVICE_ROLE_KEY"{print $2; exit}')"
mailpit_url="$(printf '%s\n' "$status_env" | awk -F= '$1=="MAILPIT_URL"{print $2; exit}')"

strip_quotes() {
    local value="$1"
    value="${value%\"}"
    value="${value#\"}"
    echo "$value"
}

api_url="$(strip_quotes "$api_url")"
anon_key="$(strip_quotes "$anon_key")"
service_role_key="$(strip_quotes "$service_role_key")"
mailpit_url="$(strip_quotes "$mailpit_url")"

if [ -z "$api_url" ] || [ -z "$anon_key" ]; then
    echo "Could not detect API_URL/ANON_KEY from supabase status."
    echo "Run: supabase status -o env"
    exit 1
fi

cat > "$ROOT_DIR/.env.local" <<EOF
# Auto-generated by scripts/setup-local-supabase.sh
VITE_SUPABASE_URL=$api_url
VITE_SUPABASE_ANON_KEY=$anon_key
SUPABASE_URL=$api_url
SUPABASE_ANON_KEY=$anon_key
SUPABASE_SERVICE_ROLE_KEY=$service_role_key
MAILPIT_URL=$mailpit_url
EOF

echo "Wrote .env.local with local Supabase keys."
echo "Run: npm run dev"
